sonar.projectKey=conde-vampiresco-espectral-trevoso_ES2_2025-2_forem
sonar.organization=conde-vampiresco-espectral-trevoso
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/__tests__/**
sonar.test.exclusions=app/javascript/article-form/components/__tests__/Title.test.jsx
sonar.exclusions=**/__tests__/**
# Se funcionar a inclusao dos testes, a referencia para a config. foi essa resposta https://community.sonarsource.com/t/use-sonar-tests-with-wildcards/34518/3.


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=ES2_2025-2_forem
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
